name: 'Generate CryptoCross'
description: 'Generate a cryptocross output file.'
inputs:
  size:  # id of input
    description: 'Number of words in the cryptocross'
    required: true
    default: 20
outputs:
  filename: # id of output
    description: 'Filename for the contents file.'
  contents: # id of output
    description: 'Base64 encoded cryptocross file contents.'
runs:
  using: 'node16'
  main: 'dist/index.js'