on: [workflow_dispatch]

jobs:
  generate_cryptocross_job:
    runs-on: ubuntu-latest
    name: A job to generate a cryptocross puzzle
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: cryptocross
        uses: ./ # Uses an action in the root directory
        id: cryptocross
        with:
          size: 20
      # Write the filename
      - name: Get the filename
        run: echo "The filame was ${{ steps.cryptocross.outputs.filename }}"
      # Write the file size
      - name: Get the file content size
        run: echo "The file contents ${{ steps.cryptocross.outputs.contents }}"
      - name: Identify Myself
        run: git config --global user.email "cryptogramsandcoffee@gmail.com"
             git config --global user.name "Cryptograms and Coffee"
      - name: Stage Changes
        run: git add .
      - name: Commit Changes
        run: git commit -m "Committing generated cryptocross files."
      - name: Fetch From Master
        run: git fetch origin master
      - name: Push Changes
        run: git push origin HEAD:master
            